- name: Install tomcat
  become: yes
  hosts: all
  vars:
          - username: tomcat
          - default_shell: /bin/false
          - group: tomcat
          - home_dir: /opt/tomcat
  tasks:
     - name: update cache
       apt:
                update_cache: yes
                when: ansible_facts['os_family'] == "Debian"

     - name: update java
       package:
               name: "{{ java_home }}"
               state: present