---
- name: install lamp
  become: yes
  hosts: appserver
  tasks:
    - name: update apt repo and cache
      apt:
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"
    - name: install jdk
      package:
        name: "{ java_package }"
      state: present      
