---
- name: Install Lamp on slack
  become: yes
  hosts: all
  tasks:
  - name: Install the latest version of Apache
    yum:
      name: httpd
      state: latest
  when: ansible_facts['os_family'] == "Debian"