---
- name: Install Lamp on slack
  become: yes
  hosts: all
  tasks:
    - name: install update on cache
      apt:
        yum:
          updae_cache: yes
      when: ansible_facts['os_family'] == "Debian"