---
- name: Install Lamp on slack
  hosts: webserver  
  tasks:
    - name: install update on cache
      apt:
        yum:
          updae_cache: yes
      when: ansible_facts['os_family'] == "Debian"
    - name: insgtall apache
      ansible.builtin.package:
        name: apache2
        state: present
      when: ansible_facts['os_family'] == "Debian"
