---
- name: Install Tomcat on RHEl
  become: yes
  hosts: AppServer
  vars: 
   - namename: tomcat
   - home_dir: /opt/tomcat
   - default_shell: /bin/false
   - tomcat_version: 9.0.6
  tasks:
- name: install yum update
  apt:
        update_cache: yes
  when: ansible_facts['os_family'] == "Debian"
 