---
- name: Install tomcat
  become: yes
  hosts: all
  vars:
          - username: tomcat
          - default_shell: /bin/false
          - group: tomcat
          - home_dir: /opt/tomcat
          - tomcat_version: 9.0.60
          - tomcat_latest: /opt/tomcat/latest
          - tomcat_bin_directory: /opt/tomcat/latest/bin
  tasks:
     - name: update cache
       apt:
                update_cache: yes
                when: ansible_facts['os_family'] == "Debian"

     - name: update java
       package:
               name: "{{ java_home }}"
               state: present
     - name: create user
       ansible.builtin.user:
               create_home: yes
               group: "{{ username }}"
               home: "{{ home_dir }}"
               name: "{{ username }}"
               shell: "{{ default_shell }}"
               state: present
     -  name: Download Tomcat
        ansible.builtin.get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{ home_dir }"
