---
- name: Install tomcat
  become: yes
  hosts: all
  vars:
          - username: tomcat
          - default_shell: /bin/false
          - group: tomcat
          - home_dir: /opt/tomcat
  tasks:
     - name: update cache
       apt:
                update_cache: yes
                when: ansible_facts['os_family'] == "Debian"

     - name: update java
       package:
               name: "{{ java_home }}"
               state: present
     - name: create user
       ansible.builtin.user:
               create_home: yes
               group: "{{ username }}"
               home: "{{ home_dir }}"
               name: "{{ username }}"
               shell: "{{ default_shell }}"
               state: present
               when: ansible_facts['os_family'] == "Debian"
