username: tomcat
home_dir: /opt/tomcat
default_shell: /bin/false
tomcat_version: 9.0.60
tomcat_latest: /opt/tomcat/latest
tomcat_bin_directory: /opt/tomcat/latest/bin/
tomcat_service_location: /etc/systemd/system/tomcat.service