---
- import_playbook: java.yml
- name: install python package
  become: yes
  hosts: all
  tasks:
    - name: update cache
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"
    - name: install jdk
      ansible.builtin.package:
      package: "{{ java_package }}"
      state: present
      when: ansible_facts['os_family'] == "Debian"
    - name: install python3
      package: "{{ item }}"
      item:
        - git
        - python
        - ssh