---
- name: install lamb on slack
  become: yes
  hosts: webserver
  tasks:
    - name: install apt updates
      apt:
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"
    - name: install apache
      ansible.builtin.package:
        package: "{{ apache_package }}"
        state: present
      when: ansible_facts['os_family'] == "Debian"
    - name: install php package
      ansible.builtin.package:
        package: "{{ item }}"
        status: present
      when: ansible_facts['os_family'] == "Debian"
      loop: "{{ php_packages }}"
      notify:
        - ensure apache is enabled and restarted
    - name: copy php info page
      ansible.builtin.copy:
        src: www/info.php
        dest: "{{ php_page_location }}"
        notify:
        - ensure apache is enabled and restarted
